Repository dm-plz/family-farm-mobile, pull requests merged in 2024-08, with the labels that each got.

#15 로그인/로그아웃 UI 구현
  App.tsx
  android/app/src/main/java/com/familyfarmrn/MainActivity.kt
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/MainHeader.tsx
  src/constants/colors.ts
  src/constants/index.ts
  src/constants/navigations.ts
  src/navigations/BottomTabNavigator.tsx
  src/navigations/RootNavigator.tsx
  src/navigations/stack/MymyStackNavigator.tsx
  src/pages/Main01.tsx
  src/pages/Mymy01.tsx
  src/pages/Sett01.tsx
Labels: 기능 추가, 빌드

#23 refactor: RootNavigator에 Navigator Stack 통합, Header 이름 변경, 폴더 구조 변경
  .eslintrc.js
  .prettierrc.js
  App.tsx
  src/components/CheckBox.tsx
  src/components/CustomButton.tsx
  src/components/my/MainHeader.tsx
  src/components/sign-up/StepHeader.tsx
  src/constants/colors.ts
  src/constants/navigations.ts
  src/hooks/useAuth.ts
  src/navigations/BottomTabNavigator.tsx
  src/navigations/RootNavigator.tsx
  src/navigations/stack/MyStackNavigator.tsx
  src/navigations/stack/SignUpStackNavigator.tsx
  src/pages/Onboarding.tsx
  src/pages/home/Main.tsx
  src/pages/my/My.tsx
  src/pages/my/Setting.tsx
  src/pages/sign-up/Join1.tsx
  src/pages/sign-up/Join2.tsx
  src/pages/sign-up/Join3.tsx
  src/pages/sign-up/Join3A.tsx
  src/pages/sign-up/Join3B.tsx
Labels: 리펙토링

#30 mock API 환경 구축 및 일부 API mocking
  .env
  .vscode/settings.json
  App.tsx
  __tests__/App.test.tsx
  index.js
  ios/FamilyFarmRN/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/FamilyFarmRN/Images.xcassets/Contents.json
  ios/Podfile.lock
  metro.config.js
  package-lock.json
  package.json
  src/api/auth.ts
  src/api/family.ts
  src/api/ky.ts
  src/api/my.ts
  src/api/queryClient.ts
  src/api/quetion.ts
  src/api/routes.ts
  src/api/survey.ts
  src/constants/api.ts
  src/constants/index.ts
  src/constants/user.ts
  src/mocks/constants/index.ts
  src/mocks/constants/oauth.ts
  src/mocks/fakers/index.ts
  src/mocks/fakers/user.ts
  src/mocks/fakers/util.ts
  src/mocks/handlers/auth.ts
  src/mocks/handlers/family.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/my.ts
  src/mocks/handlers/question.ts
  src/mocks/handlers/survey.ts
  src/mocks/init.ts
  src/mocks/msw.polyfills.js
  src/mocks/server.ts
  src/mocks/utils/api.ts
  src/mocks/utils/token.ts
  src/types/auth.ts
  src/types/index.ts
  src/types/question.ts
  src/types/survey.ts
  src/types/user.ts
  src/utils/date.ts
  src/utils/encryptStorage.ts
  src/utils/index.ts
  src/utils/string.ts
  src/utils/token.ts
  src/utils/url.ts
  style-config.md
  tsconfig.json
Labels: 기능 추가, 빌드

#43 fix: msw intercept error
  src/api/question.ts
  src/api/routes.ts
  src/mocks/handlers/question.ts
  src/utils/url.ts
Labels: 버그 수정

#45 Feature/oauth
  .gitignore
  android/app/build.gradle
  android/app/google-services.json
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/familyfarmrn/KakaoLoginModule.kt
  android/app/src/main/java/com/familyfarmrn/KakaoLoginPackage.kt
  android/app/src/main/java/com/familyfarmrn/MainActivity.kt
  android/app/src/main/java/com/familyfarmrn/MainApplication.kt
  android/build.gradle
  ios/AppleLoginModule.m
  ios/AppleLoginModule.swift
  ios/FamilyFarmRN-Bridging-Header.h
  ios/FamilyFarmRN.xcodeproj/project.pbxproj
  ios/FamilyFarmRN/AppDelegate.mm
  ios/FamilyFarmRN/FamilyFarmRN.entitlements
  ios/FamilyFarmRN/Info.plist
  ios/FamilyFarmRN/KakaoSignInModule.swift
  ios/FamilyFarmRN/PrivacyInfo.xcprivacy
  ios/KakaoLoginModule.h
  ios/KakaoLoginModule.m
  ios/KakaoLoginModule.swift
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  src/pages/Onboarding.tsx
  src/utils/oauth.ts
Labels: 기능 추가, 빌드

#41 Feat: Feature/question 구현 완료
  App.tsx
  gesture-handler.js
  gesture-handler.native.js
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/question-answer/MyIcon.tsx
  src/constants/bottomTab.ts
  src/constants/index.ts
  src/constants/navigations.ts
  src/hooks/useAuth.ts
  src/navigations/BottomTabNavigator.tsx
  src/navigations/stack/MyStackNavigator.tsx
  src/navigations/stack/QuestionAnswerStackNavigator.tsx
  src/pages/question-answer/AnswerWithFeeling.tsx
  src/pages/question-answer/AnswerWithImage.tsx
  src/pages/question-answer/AnswerWithStringVoice.tsx
  src/pages/question-answer/QuestionList.tsx
  src/pages/question-answer/ViewAnswer.tsx
  src/utils/dayjs.js
Labels: 기능 추가
